# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@iden3/bigarray-0.0.2" = {
      name = "_at_iden3_slash_bigarray";
      packageName = "@iden3/bigarray";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iden3/bigarray/-/bigarray-0.0.2.tgz";
        sha512 = "Xzdyxqm1bOFF6pdIsiHLLl3HkSLjbhqJHVyqaTxXt3RqXBEnmsUmEW47H7VOi/ak7TdkRpNkxjyK5Zbkm+y52g==";
      };
    };
    "@iden3/binfileutils-0.0.11" = {
      name = "_at_iden3_slash_binfileutils";
      packageName = "@iden3/binfileutils";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iden3/binfileutils/-/binfileutils-0.0.11.tgz";
        sha512 = "LylnJoZ0CTdgErnKY8OxohvW4K+p6UHD3sxt+3P9AmMyBQjYR4IpoqoYZZ+9aMj89cmCQ21UvdhndAx04er3NA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "async-3.2.5" = {
      name = "async";
      packageName = "async";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.5.tgz";
        sha512 = "baNZyqaaLhyLVKm/DlvdW051MSgO6b8eVfIezl9E5PqWxFgzLm/wQntEW4zOytVburDEr0JlALEpdOFwvErLsg==";
      };
    };
    "b4a-1.6.4" = {
      name = "b4a";
      packageName = "b4a";
      version = "1.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/b4a/-/b4a-1.6.4.tgz";
        sha512 = "fpWrvyVHEKyeEvbKZTVOeZF3VSKKWtJxFIxX/jaVPf+cLbGUSitjb49pHLqPV2BUNNZ0LcoeEGfE/YCpyDYHIw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "bfj-7.1.0" = {
      name = "bfj";
      packageName = "bfj";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bfj/-/bfj-7.1.0.tgz";
        sha512 = "I6MMLkn+anzNdCUp9hMRyui1HaNEUCco50lxbvNS4+EyXg8lN3nJ48PjPWtbH8UVS9CuMoaKE9U2V3l29DaRQw==";
      };
    };
    "blake2b-wasm-2.4.0" = {
      name = "blake2b-wasm";
      packageName = "blake2b-wasm";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/blake2b-wasm/-/blake2b-wasm-2.4.0.tgz";
        sha512 = "S1kwmW2ZhZFFFOghcx73+ZajEfKBqhP82JMssxtLVMxlaPea1p9uoLiUZ5WYyHn0KddwbLc+0vh4wR0KBNoT5w==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "check-types-11.2.3" = {
      name = "check-types";
      packageName = "check-types";
      version = "11.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/check-types/-/check-types-11.2.3.tgz";
        sha512 = "+67P1GkJRaxQD6PKK0Et9DhwQB+vGg3PM5+aavopCpZT1lj9jeqfvpgTLAWErNj8qApkkmXlu/Ug74kmhagkXg==";
      };
    };
    "circom_runtime-0.1.24" = {
      name = "circom_runtime";
      packageName = "circom_runtime";
      version = "0.1.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/circom_runtime/-/circom_runtime-0.1.24.tgz";
        sha512 = "H7/7I2J/cBmRnZm9docOCGhfxzS61BEm4TMCWcrZGsWNBQhePNfQq88Oj2XpUfzmBTCd8pRvRb3Mvazt3TMrJw==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "ejs-3.1.9" = {
      name = "ejs";
      packageName = "ejs";
      version = "3.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-3.1.9.tgz";
        sha512 = "rC+QVNMJWv+MtPgkt0y+0rVEIdbtxVADApW9JXrUVlzHetgcyczP/E7DJmWJ4fJCZF2cPcBk0laWO9ZHMG3DmQ==";
      };
    };
    "escodegen-1.14.3" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.14.3.tgz";
        sha512 = "qFcX0XJkdg+PB3xjZZG/wKSuT1PnQWx57+TVSjIMmILd2yC/6ByYElPwJnslDsuWuSAp4AwJGumarAAmJch5Kw==";
      };
    };
    "esprima-1.2.2" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.2.2.tgz";
        sha512 = "+JpPZam9w5DuJ3Q67SqsMGtiHKENSMRVoxvArfJZK01/BfLEObtZ6orJa/MtoGNR/rfMgp5837T41PAmTwAv/A==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "estraverse-4.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.3.0.tgz";
        sha512 = "39nnKffWz8xN1BU/2c79n9nB9HDzo0niYUqx6xyqUnyoAnQyyWpOTdZEeiCch8BBu515t4wp9ZmgVfVhn9EBpw==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha512 = "DCXu6Ifhqcks7TZKY3Hxp3y6qphY5SJZmrWMDrKcERSOXWQdMhU9Ig/PYrzyw/ul9jOIyh0N4M0tbC5hodg8dw==";
      };
    };
    "fastfile-0.0.20" = {
      name = "fastfile";
      packageName = "fastfile";
      version = "0.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastfile/-/fastfile-0.0.20.tgz";
        sha512 = "r5ZDbgImvVWCP0lA/cGNgQcZqR+aYdFx3u+CtJqUE510pBUVGMn4ulL/iRTI4tACTYsNJ736uzFxEBXesPAktA==";
      };
    };
    "ffjavascript-0.2.60" = {
      name = "ffjavascript";
      packageName = "ffjavascript";
      version = "0.2.60";
      src = fetchurl {
        url = "https://registry.npmjs.org/ffjavascript/-/ffjavascript-0.2.60.tgz";
        sha512 = "T/9bnEL5xAZRDbQoEMf+pM9nrhK+C3JyZNmqiWub26EQorW7Jt+jR54gpqDhceA4Nj0YctPQwYnl8xa52/A26A==";
      };
    };
    "filelist-1.0.4" = {
      name = "filelist";
      packageName = "filelist";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/filelist/-/filelist-1.0.4.tgz";
        sha512 = "w1cEuf3S+DrLCQL7ET6kz+gmlJdbq9J7yXCSjK/OZCPA+qEN1WyF4ZAf0YYJa4/shHJra2t/d/r8SV4Ji+x+8Q==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hoopy-0.1.4" = {
      name = "hoopy";
      packageName = "hoopy";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoopy/-/hoopy-0.1.4.tgz";
        sha512 = "HRcs+2mr52W0K+x8RzcLzuPPmVIKMSv97RGHy0Ea9y/mpcaK+xTrjICA04KAHi4GRzxliNqNJEFYWHghy3rSfQ==";
      };
    };
    "jake-10.8.7" = {
      name = "jake";
      packageName = "jake";
      version = "10.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/jake/-/jake-10.8.7.tgz";
        sha512 = "ZDi3aP+fG/LchyBzUM804VjddnwfSfsdeYkwt8NcbKRvo4rFkjhs456iLFn3k2ZUWvNe4i48WACDbza8fhq2+w==";
      };
    };
    "js-sha3-0.8.0" = {
      name = "js-sha3";
      packageName = "js-sha3";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz";
        sha512 = "gF1cRrHhIzNfToc802P800N8PpXS+evLLXfsVpowqmAFR9uwbi89WvXg2QspOmXL8QL86J4T1EpFu+yUkwJY3Q==";
      };
    };
    "jsonpath-1.1.1" = {
      name = "jsonpath";
      packageName = "jsonpath";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpath/-/jsonpath-1.1.1.tgz";
        sha512 = "l6Cg7jRpixfbgoWgkrl77dgEj8RPvND0wMH6TwQmi9Qs4TFfS9u5cUFnbeKTwj5ga5Y3BTGGNI28k117LJ009w==";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha512 = "0OO4y2iOHix2W6ujICbKIaEQXvFQHue65vUG3pb5EUomzPI90z9hsA1VsO/dbIIpC53J8gxM9Q4Oho0jrCM/yA==";
      };
    };
    "logplease-1.2.15" = {
      name = "logplease";
      packageName = "logplease";
      version = "1.2.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/logplease/-/logplease-1.2.15.tgz";
        sha512 = "jLlHnlsPSJjpwUfcNyUxXCl33AYg2cHhIf9QhGL2T4iPT0XPB+xP1LRKFPgIg1M/sg9kAJvy94w9CzBNrfnstA==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimatch-5.1.6" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "5.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-5.1.6.tgz";
        sha512 = "lKwV/1brpG6mBUFHtb7NUmtABCb2WZZmm2wNiOA5hAb8VdCS4B3dtMWyvcoViccwAW/COERjXLt0zP1zXUN26g==";
      };
    };
    "nanoassert-2.0.0" = {
      name = "nanoassert";
      packageName = "nanoassert";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoassert/-/nanoassert-2.0.0.tgz";
        sha512 = "7vO7n28+aYO4J+8w96AzhmU8G+Y/xpPDJz/se19ICsqj/momRbb9mh9ZUtkoJ5X3nTnPdhEJyc0qnM6yAsHBaA==";
      };
    };
    "optionator-0.8.3" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.3.tgz";
        sha512 = "+IW9pACdk3XWmmTXG8m3upGUJst5XRGzxMRjXzAuJ1XnIFNvfhjjIuYkDvysnPQ7qzqVzLt78BCruntqRhWQbA==";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha512 = "ESF23V4SKG6lVSGZgYNpbsiaAkdab6ZgOxe52p7+Kid3W3u3bxR4Vfd/o21dmN7jSt0IwgZ4v5MUd26FEtXE9w==";
      };
    };
    "r1csfile-0.0.47" = {
      name = "r1csfile";
      packageName = "r1csfile";
      version = "0.0.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/r1csfile/-/r1csfile-0.0.47.tgz";
        sha512 = "oI4mAwuh1WwuFg95eJDNDDL8hCaZkwnPuNZrQdLBWvDoRU7EG+L/MOHL7SwPW2Y+ZuYcTLpj3rBkgllBQZN/JA==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "static-eval-2.0.2" = {
      name = "static-eval";
      packageName = "static-eval";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/static-eval/-/static-eval-2.0.2.tgz";
        sha512 = "N/D219Hcr2bPjLxPiV+TQE++Tsmrady7TqAJugLy7Xk1EumfDWS/f5dtBbkRCGE7wKKXuYockQoj8Rm2/pVKyg==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "tryer-1.0.1" = {
      name = "tryer";
      packageName = "tryer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tryer/-/tryer-1.0.1.tgz";
        sha512 = "c3zayb8/kWWpycWYg87P71E1S1ZL6b6IJxfb5fvsUgsf0S2MVGaDhDXXjDMpdCpfWXqptc+4mXwmiy1ypXqRAA==";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha512 = "ZCmOJdvOWDBYJlzAoFkC+Q0+bUyEOS1ltgp1MGU03fqHG+dbi9tBFU2Rd9QKiDZFAYrhPh2JUf7rZRIuHRKtOg==";
      };
    };
    "underscore-1.12.1" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.12.1.tgz";
        sha512 = "hEQt0+ZLDVUMhebKxL4x1BTtDY7bavVofhZ9KZ4aI26X9SRaE+Y3m83XUL1UP2jn8ynjndwCCpEHdUG+9pP1Tw==";
      };
    };
    "wasmbuilder-0.0.16" = {
      name = "wasmbuilder";
      packageName = "wasmbuilder";
      version = "0.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/wasmbuilder/-/wasmbuilder-0.0.16.tgz";
        sha512 = "Qx3lEFqaVvp1cEYW7Bfi+ebRJrOiwz2Ieu7ZG2l7YyeSJIok/reEQCQCuicj/Y32ITIJuGIM9xZQppGx5LrQdA==";
      };
    };
    "wasmcurves-0.2.2" = {
      name = "wasmcurves";
      packageName = "wasmcurves";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wasmcurves/-/wasmcurves-0.2.2.tgz";
        sha512 = "JRY908NkmKjFl4ytnTu5ED6AwPD+8VJ9oc94kdq7h5bIwbj0L4TDJ69mG+2aLs2SoCmGfqIesMWTEJjtYsoQXQ==";
      };
    };
    "web-worker-1.2.0" = {
      name = "web-worker";
      packageName = "web-worker";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-worker/-/web-worker-1.2.0.tgz";
        sha512 = "PgF341avzqyx60neE9DD+XS26MMNMoUQRz9NOZwW32nPQrF6p77f1htcnjBSEV8BGMKZ16choqUG4hyI0Hx7mA==";
      };
    };
    "word-wrap-1.2.5" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.5.tgz";
        sha512 = "BN22B5eaMMI9UMtjrGd5g5eCYPpCPDUy0FJXbYsaT5zYxjFOckS53SQDE3pWkVoWpHXVb3BrYcEN4Twa55B5cA==";
      };
    };
  };
  args = {
    name = "snarkjs";
    packageName = "snarkjs";
    version = "0.7.1";
    src = ./.;
    dependencies = [
      sources."@iden3/bigarray-0.0.2"
      sources."@iden3/binfileutils-0.0.11"
      sources."ansi-styles-4.3.0"
      sources."async-3.2.5"
      sources."b4a-1.6.4"
      sources."balanced-match-1.0.2"
      sources."bfj-7.1.0"
      sources."blake2b-wasm-2.4.0"
      sources."bluebird-3.7.2"
      sources."brace-expansion-2.0.1"
      sources."chalk-4.1.2"
      sources."check-types-11.2.3"
      sources."circom_runtime-0.1.24"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."concat-map-0.0.1"
      sources."deep-is-0.1.4"
      sources."ejs-3.1.9"
      (sources."escodegen-1.14.3" // {
        dependencies = [
          sources."esprima-4.0.1"
        ];
      })
      sources."esprima-1.2.2"
      sources."estraverse-4.3.0"
      sources."esutils-2.0.3"
      sources."fast-levenshtein-2.0.6"
      sources."fastfile-0.0.20"
      sources."ffjavascript-0.2.60"
      (sources."filelist-1.0.4" // {
        dependencies = [
          sources."minimatch-5.1.6"
        ];
      })
      sources."has-flag-4.0.0"
      sources."hoopy-0.1.4"
      sources."jake-10.8.7"
      sources."js-sha3-0.8.0"
      sources."jsonpath-1.1.1"
      sources."levn-0.3.0"
      sources."logplease-1.2.15"
      (sources."minimatch-3.1.2" // {
        dependencies = [
          sources."brace-expansion-1.1.11"
        ];
      })
      sources."nanoassert-2.0.0"
      sources."optionator-0.8.3"
      sources."prelude-ls-1.1.2"
      sources."r1csfile-0.0.47"
      sources."source-map-0.6.1"
      sources."static-eval-2.0.2"
      sources."supports-color-7.2.0"
      sources."tryer-1.0.1"
      sources."type-check-0.3.2"
      sources."underscore-1.12.1"
      sources."wasmbuilder-0.0.16"
      sources."wasmcurves-0.2.2"
      sources."web-worker-1.2.0"
      sources."word-wrap-1.2.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "zkSNARKs implementation in JavaScript";
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
